.devcontainer/devcontainer.json
.github/workflows/cloudformation.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
README.md
cloudformation/account_resources.yml
cloudformation/ci_resources.yml
cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json
scripts/set_secrets.sh

- add granular roles for deployment steps
-- CloudFormationCheckVersionRole - used to check deployed versions of stacks
-- ReleaseNotesExecuteLambdaRole - used to execute the release notes lambda
-- CloudFormationPrepareChangesetRole - used to create changesets (but not execute them)
- adds script to set secrets in all our repos
- adds github cli to devcontainer

add more granular roles

---

cloudformation/ci_resources.yml
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json

remove empty claims

---

cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json

- Put an empty string in filters if its not used

use empty string in array

---

cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json

- use NONE in subject claim filters instead of empty string

use none in filters

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- use static tags for some resources to prevent them being changed

use static version tags for some objects

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

Fix tags in static tags

---

cloudformation/ci_resources.yml

fix output

---

.github/actions/mark_jira_released/action.yml
.github/actions/update_confluence_jira/action.yml
.github/workflows/create_confluence_release_notes.yml
.github/workflows/release.yml

- adds steps to release workflow to create release notes

add code to create release notes

---

.github/actions/update_confluence_jira/action.yml

- clear AWS credentials before trying to run lambda

clear aws credentials

---

.github/workflows/create_confluence_release_notes.yml

- do not do prod release notes until we do a prod deployment

do not do prod release notes yet

---

.github/workflows/cloudformation.yml
.github/workflows/pull_request.yml
cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- When displaying changes, also do it for existing tags so that it is easier to identify changes

create changeset using existing tags to help identify changes

---

.github/workflows/cloudformation.yml

change output slightly

---

cloudformation/ci_resources.yml

After the EnableKeyRotation was added there should also be a relative premission on the IAM policy.
Adds "kms:EnableKeyRotation" in IAM policy.

AEA-3488 (AWS-03) Key rotation is disabled - Policy Update

---

cloudformation/ci_resources.yml

- allow deploy role to assume apigw service so it can add policies

allow execution role to assume apigw

---

.github/workflows/cloudformation.yml

- handle UPDATE_COMPLETE_CLEANUP_IN_PROGRESS status while waiting for changeset to deploy

handle UPDATE_COMPLETE_CLEANUP_IN_PROGRESS status

---

SAMtemplates/lambda_resources.yaml

- change condition for KMS key so it can access insights group correctly

change kms context for insights

---

cloudformation/ci_resources.yml

- add ListTagsForResource permission to deploy execute role

add missing permisson for ListTagsForResource

---

.github/workflows/release.yml

- add back in output_changeset_version to release workflow

add back in output_changeset_version

---

.github/workflows/create_confluence_release_notes.yml

- create prod release notes page in confluence

create prod release notes page

---

.github/workflows/delete_old_cloudformation_stacks.yml

- add workflow to delete old cloudformation stacks

add workflow to delete old cloudformation stacks

---

cloudformation/ci_resources.yml

- ads logs:TagResource permission to cloudformation execute role

add logs:tagresource permission to execute role

---

SAMtemplates/lambda_resources.yaml

Adds additional actions to Lambda Insights Log group policy to enable KMS key actions.
Adds additional kms key actions to policy.

AEA-3735 enable lambda insights

---

.github/workflows/dependabot_auto_approve_and_merge.yml

- add action to autoapprove dependabot pull requests

add action to autoapprove dependabot pull requests

---

.github/workflows/release_all_stacks.yml
SAMtemplates/lambda_resources.yaml
cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- Merged Cloudwatch KMS keys
- Updated Inline policies to managed policies
- Rearranged file contents to better group resources for aid in readability and maintainability
- Updated CF files to standardise formatting and implementations for consistency
- Added lambda related policies from PFP

[AEA-3755] IAM Policy Refactor (Except SAM)

---

cloudformation/ci_resources.yml

- Adds BucketPolicy permissions

[AEA-3755] Adds BucketPolicy permissions

---

SAMtemplates/lambda_resources.yaml
cloudformation/account_resources.yml

Part 2 of https://github.com/NHSDigital/electronic-prescription-service-account-resources/pull/78

[AEA-3755] IAM Policy Refactor (Just SAM)

---

SAMtemplates/lambda_resources.yaml
cloudformation/account_resources.yml

- Updates Managed Policy resource names to differentiate from old inline versions 

[AEA-3755] Updates policy resource names

---

sonar-project.properties

- fix sonar-project.properties to point to correct project

fix sonar project properties

---

sonar-project.properties

- remove sonar-project.properties as its not needed

remove sonar-project.properties

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml
cloudformation/env/dev.json

- add test reports bucket
- add role for test reports bucket

Add bucket and role for test reports

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml
cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json

- add permission needed to create s3 bucket
- delete s3 bucket as its not needed

delete s3 bucket and put correct role in policy

---

SAMtemplates/lambda_resources.yaml
scripts/calculate_version.py

+clearstatus
- correct calculate version script to look at whole message for command

correct calculate version

---

.devcontainer/devcontainer.json
cloudformation/ci_resources.yml
cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json
scripts/set_secrets.sh

- grant access to the following repositories
- eps-FHIR-validator-lambda 
- eps-prescription-status-update-api repositories
- add lambda:CreateAlias permission to cloudformation deploy role

grant access to new repositories

---

cloudformation/account_resources.yml

- adds secrets for proxygen public/private key

secrets for proxygen public/private key

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

Adds state machine permissions to the Cloudformation deploy role and adds a generic cloudwatch encryption policy.

[AEA-3831] State Machine supporting infra

---

cloudformation/account_resources.yml

Adds Step Functions log groups to CLoudwatch KMS key permissions

[AEA-3831] adds step function log group to kms permissions

---

cloudformation/ci_resources.yml

🎫 [AEA-3859](https://nhsd-jira.digital.nhs.uk/browse/AEA-3859) Create Apigee proxy for PSU API
Add CloudFormation secret policy

AEA-3859 Add CloudFormation secret policy

---

cloudformation/ci_resources.yml

🎫 [AEA-3859](https://nhsd-jira.digital.nhs.uk/browse/AEA-3859) Create Apigee proxy for PSU API
Change CloudFormation secret policy action

AEA-3859 Change CloudFormation secret policy action

---

.devcontainer/devcontainer.json
.github/workflows/pull_request.yml
.github/workflows/quality_checks.yml
.github/workflows/release.yml
package-lock.json
package.json
packages/splunkProcessor/src/splunkProcessor.js
packages/splunkProcessor/tests/transformLogEvent.lambda.test.js
packages/splunkProcessor/tests/transformLogEvent.other.test.js
packages/splunkProcessor/tests/transformLogEvent.stepfunctions.test.js
packages/splunkProcessor/tests/transformLogEvent.test.js
sonar-project.properties

- extract correlation ids for step functions
- add sonar cloud coverage
- add jest and prettier vscode plugins to dev container

AEA-3991 extract correlation ids for step functions

---

cloudformation/env/int.json
cloudformation/env/prod.json

- use correct subject claim filter for PSU int and prod deployments

AEA-0000 fix psu int deployments

---

cloudformation/ci_resources.yml

- add missing permissions to CloudFormationExecutionRole

Fix: [AEA-0000] - add missing permissions to CloudFormationExecutionRole

---

cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json

Adds account resources permissions to fhir facade for proxygen deployment

AEA-3918 Adds account resources permissions to fhir facade

---

cloudformation/ci_resources.yml

Add permissions for application autoscaling

Fix: [AEA-0000] - Add permissions for application autoscaling

---

cloudformation/ci_resources.yml

Add policies for application autoscaling

Fix: [AEA-0000] - Add policies for application autoscaling

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- fix roles for dynamo scaling (application-autoscaling:DescribeScheduledActions and some cloudwatch: permissions)
- correct typos on s3, kms, logs actions

Fix: [AEA-0000] - fix roles for dynamo scaling

---

cloudformation/ci_resources.yml

- add back in apigateway:TagResource permission

Fix: [AEA-0000] - add back in tag resource

---

.github/dependabot.yml

- add npm to dependabot config

Fix: [AEA-0000] - add node dependabot

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- create separate proxygen keys for psu and cpsu. This is a prerequisite for AEA-4166

Fix: [AEA-0000] - add seperate proxygen keys for PSU and CPSU

---

.github/scripts/create_changeset_existing_tags.sh
.github/scripts/create_changeset_new_tags.sh

- wait for stack to finish update or create

Fix: [AEA-0000] - wait for stack to finish update or create

---

.github/pull_request_template.md
.github/workflows/pr_title_check.yml
.github/workflows/pull_request.yml

- check format of title of pull requests

Fix: [AEA-0000] - add check for title of pull requests

---

cloudformation/ci_resources.yml

- Adds additional ec2 permissions

Fix: [AEA-3924] - Add missing ec2 permissions 

---

cloudformation/ci_resources.yml
cloudformation/env/int.json
cloudformation/env/prod.json

- more restrictive permissions on PrepareChangesetClaimFilters in int and prod
- separate IAM policy restricted to specific AWS account

Fix: [AEA-4225] - more restrictive IAM policies

---

cloudformation/env/int.json
cloudformation/env/prod.json

- use branch name in claim filter for prepare changeset

Fix: [AEA-0000] - use branch name in claim filter for create changeset

---

SECURITY.md

Docs: [AEA-4304] - add security.md

---

cloudformation/ci_resources.yml

🎫 [AEA-4322](https://nhsd-jira.digital.nhs.uk/browse/AEA-4322) Grant elasticloadbalancing permissions
Grant elasticloadbalancing permissions.

Chore: [AEA-4322] - Grant elasticloadbalancing permissions

---

cloudformation/ci_resources.yml

🎫 [AEA-4322](https://nhsd-jira.digital.nhs.uk/browse/AEA-4322) Grant elasticloadbalancing permissions
Grant elasticloadbalancing permissions - include AddTags.

Fix: [AEA-4322] - Grant elasticloadbalancing permissions - include AddTags

---

SAMtemplates/lambda_resources.yaml

- add intenal-dev-sandbox to ptl instance get and delete

Fix: [AEA-0000] - add internal-dev-sandbox to ptl instance get and delete

---

cloudformation/ci_resources.yml

Fix: [AEA-0000] - add missing ecr policy

---

cloudformation/ci_resources.yml

🎫 [AEA-4335](https://nhsd-jira.digital.nhs.uk/browse/AEA-4335) Add elasticloadbalancing permissions
Add elasticloadbalancing permissions

Chore: [AEA-4335] - Add elasticloadbalancing permissions

---

cloudformation/ci_resources.yml

- add update TTL permission for dymanodb

Fix: [AEA-4342] - add update ttl for dynamodb permission 

---

cloudformation/ci_resources.yml

🎫 [AEA-4363](https://nhsd-jira.digital.nhs.uk/browse/AEA-4363) Grant elasticloadbalancing security group permissions
Grant elasticloadbalancing security group permissions.

Chore: [AEA-4363] - Grant elasticloadbalancing security group permissions

---

cloudformation/ci_resources.yml

🎫 [AEA-4373](https://nhsd-jira.digital.nhs.uk/browse/AEA-4373) Grant ECS permissions to ci-resources stack
Grant Elastic Container Service permissions to ci-resources stack.

Chore: [AEA-4373] - Grant ECS permissions

---

cloudformation/ci_resources.yml

Fix: [AEA-4292] - Adds Create NACL permission

---

cloudformation/ci_resources.yml
cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json

- add permissions to delete CNAMES in dev

Fix: [AEA-4386] - add permissions to delete cnames to dev

---

cloudformation/ci_resources.yml

Fix: [AEA-4292] - Adds Describe NACL permission

---

cloudformation/ci_resources.yml

- delete CNAME policy has to act on * resource

Fix: [AEA-0000] - fix delete cname policy

---

cloudformation/ci_resources.yml

- add some more network acl policies

Fix: [AEA-0000] - more ACL policies

---

cloudformation/ci_resources.yml

- adds elasticloadbalancing:ModifyTargetGroup as needed for fhir repo

Fix: [AEA-0000] - add ModifyTargetGroup permission

---

cloudformation/account_resources.yml

🎫 [AEA-4352](https://nhsd-jira.digital.nhs.uk/browse/AEA-4352) Create 2 new proxygen secrets for clinical tracker for proxygen
Create 2 new proxygen secrets for clinical tracker for proxygen

Update: [AEA-4352] - Create 2 new proxygen secrets for clinical tracker for proxygen

---

SAMtemplates/lambda_resources.yaml
cloudformation/ci_resources.yml

🎫 [AEA-4352](https://nhsd-jira.digital.nhs.uk/browse/AEA-4352)  Modify policies for Clinical Tracker
Modify policies for Clinical Tracker.

Update: [AEA-4352] - Modify policies for Clinical Tracker

---

packages/proxygen/src/helpers.ts
packages/proxygen/src/proxygenInstanceDelete.ts
packages/proxygen/src/proxygenInstanceGet.ts
packages/proxygen/src/proxygenInstancePut.ts
packages/proxygen/src/proxygenMTLSSecretPut.ts
packages/proxygen/src/proxygenSpecPublish.ts
packages/proxygen/tests/proxygenInstanceDelete.test.ts
packages/proxygen/tests/proxygenInstanceGet.test.ts
packages/proxygen/tests/proxygenInstancePut.test.ts
packages/proxygen/tests/proxygenMTLSSecretPut.test.ts
packages/proxygen/tests/proxygenSpecPublish.test.ts

- better proxygen error logging

Fix: [AEA-4385] - better proxygen error logging

---

SAMtemplates/lambda_resources.yaml
cloudformation/ci_resources.yml

- Adds permissions for creating / managing cloudwatch alarms and metrics
- Adds export for slack alerter sns topic

Chore: [AEA-4423] - Add Alarm & Metric permissions

---

packages/proxygen/src/helpers.ts
packages/proxygen/src/proxygenSpecPublish.ts
packages/proxygen/tests/proxygenSpecPublish.test.ts

Fix: [AEA-0000] - correct spec publish

---

cloudformation/ci_resources.yml

- add permission to view ecr scan results

Fix: [AEA-0000] - add permissions to view ecr scan results

---

cloudformation/ci_resources.yml

- add ec2:DescribeAccountAttributes permission to CloudFormationExecutionRole

Fix: [AEA-0000] - add ec2:DescribeAccountAttributes permission

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml
cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json
scripts/set_secrets.sh

- add permissions for clinical tracker ui repo
- add claim filter so clinical tracker can use proxygen lambdas

Fix: [AEA-0000] - add clincial tracker up repo

---

cloudformation/account_resources.yml

- Adds export for Secrets KMS Key Alias

Chore: [AEA-4405] - Add export for Secrets KMS key

---

.github/workflows/cloudformation.yml
.github/workflows/release_all_stacks.yml

- add comments about adding new stack

Docs: [AEA-0000] - add some comments about adding new stack

---

README.md
cloudformation/artillery_resources.yml

Add a security group that references the VPC, which will be used by Artillery for load testing.

Update: [AEA-4067] - load testing

---

scripts/bootstrap-cdk.sh

- fix the cdk bootstrap script so it gets correct ARNs

Fix: [AEA-0000] - fix cdk bootstrap script

---

cloudformation/ci_resources.yml

- add permissions to assume lookup role

Fix: [AEA-0000] - add cdk lookup role

---

cloudformation/ci_resources.yml

- add  SNS:GetDataProtectionPolicy permission

Fix: [AEA-0000] - add missing sns permission

---

cloudformation/account_resources.yml

- add kms permission to cloudwatch kms key to deploy role

Fix: [AEA-0000] - add kms permission to cloudwatch kms key to deploy role

---

cloudformation/ci_resources.yml
cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json
scripts/set_secrets.sh

🎫 [AEA-4526](https://nhsd-jira.digital.nhs.uk/browse/AEA-4526) Grant access to eps-aws-dashboards repository
- Grant access to the eps-aws-dashboards repository 
- Add required cloudwatch dashboard permissions

Chore: [AEA-4526] - Grant access to eps-aws-dashboards repository

---

cloudformation/ci_resources.yml

- add missing elb and ecs permissions needed for deployment
- remove invalid permissions

Fix: [AEA-0000]  - fix elb permissions

---

cloudformation/ci_resources.yml

- add back in apigateway:TagResource permission

Fix: [AEA-0000] - add back in apigateway:TagResource permission

---

SAMtemplates/lambda_resources.yaml

- add stack name to the alarm name

Fix: [AEA-000] - fix alarm name

---

cloudformation/account_resources.yml

- allow prepare changeset role to use s3 artifact

Fix: [AEA-0000] - allow prepare changeset role to use s3 artifact bucket

---

.github/scripts/create_changeset_existing_tags.sh
.github/scripts/create_changeset_new_tags.sh
cloudformation/account_resources.yml

- upload cloud formation templates to s3

Fix: [AEA-0000] - upload cloud formation templates to s3

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml
cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json
scripts/set_secrets.sh

- create cdk utils ecr
- create roles to push and pull from cdk utils ecr

Fix: [AEA-4539] - create cdk utils ecr

---

cloudformation/ci_resources.yml

- add missing ecr policies to CDKPushImageRole

Fix: [AEA-0000] - add missing ecr policies to CDKPushImageRole

---

cloudformation/ci_resources.yml

- Adds permissions for cloudfront to ci deployment role

Chore: [AEA-4542] - Adds Cloudfront Permissions

---

cloudformation/ci_resources.yml

- kms.GenerateDataKey permissions for cdk deployments

Fix: [AEA-0000] - kms permissions for cdk deploy

---

cloudformation/ci_resources.yml

🎫 [AEA-4562](https://nhsd-jira.digital.nhs.uk/browse/AEA-4562) Grant NACL permission
Grant NACL permissions

Chore: [AEA-4562] - Grant NACL permissions

---

cloudformation/ci_resources.yml

- add cloudformation permissions to execute role

Fix: [AEA-0000] -  add cloudformation permissions to execute role

---

cloudformation/account_resources.yml

Adds bucket for cloudfront logs

Chore: [AEA-0000]  - adds logging bucket for cloudfront

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- Enable ACLs for cloudfront logging bucket

Chore: [AEA-0000] - Enable ACLs for cloudfront logging bucket

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- Tweaks config for cloudfront logging bucket

Chore: [AEA-0000] - Tweak cloudfront logging bucket config

---

SAMtemplates/lambda_resources.yaml
cloudformation/ci_resources.yml
cloudformation/env/prod.json

🎫 [AEA-4626](https://nhsd-jira.digital.nhs.uk/browse/AEA-4626) Grant permissions to access Secrets Manager
Grant permissions to access Secrets Manager

Chore: [AEA-4626] - Grant permissions to access Secrets Manager

---

cloudformation/ci_resources.yml

- add permissions to use and modify cloudfront-keyvalue store to deploy role

Fix: [AEA-0000] - add permissions for cloudfront keyvalue store

---

cloudformation/ci_resources.yml

- add kvs permission to run invalidation
- permission for cdk lambda custom resource

Fix: [AEA-0000] - more permissions for cpt-ui deployment

---

cloudformation/ci_resources.yml

- add secretmanager:PutResourcePolicy to deployment role

Fix: [AEA-0000] - more policy for cpt-ui

---

cloudformation/account_resources.yml

- add a dashboard viewer policy

Fix: [AEA-4678] - add DashboardViewerPolicy

---

cloudformation/account_resources.yml

Fix: [AEA-4678] - fix dashboard policy

---

cloudformation/secrets.yml

🎫 [AEA-4733](https://nhsd-jira.digital.nhs.uk/browse/AEA-4733) Add Proxygen key outputs for fhir-prescribing and fhir-dispensing APIs
Add Proxygen key outputs for fhir-prescribing and fhir-dispensing APIs

Chore: [AEA-4733] - Add Proxygen key outputs for fhir-prescribing and fhir-dispensing APIs

---

cloudformation/account_resources.yml

- correct permissions for dashboard viewer

Fix: [AEA-0000] - correct permissions for dashboard viewer

---

cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json
scripts/set_secrets.sh

Adds new eps-vpc-resources to list of repos for set secrets

Chore: [AEA-0000] - Update repo list for set secrets

---

.github/workflows/cloudformation.yml
cloudformation/account_resources.yml

Fix: [AEA-4544] - create ALB logs bucket

---

SAMtemplates/lambda_resources.yaml

🎫 [AEA-4749](https://nhsd-jira.digital.nhs.uk/browse/AEA-4749) Grant permissions to access Proxygen secrets
Grant permissions to access Proxygen secrets:
- secrets:FhirPrescribingProxygenPrivateKey
- secrets:FhirDispensingProxygenPrivateKey

Chore: [AEA-4749] - Grant permissions to access Proxygen secrets

---

.pre-commit-config.yaml
cloudformation/account_resources.yml

- create athena results bucket

Fix: [AEA-0000] - create Athena results bucket

---

cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json
scripts/set_secrets.sh

- add eps-storage-resources repo to claim filters

Fix: [AEA-4575] - add eps-storage-resources repo to claim filters

---

cloudformation/ci_resources.yml
scripts/bootstrap-cdk.sh

- Adds output for ec2 permissions policy
- Updates cdk bootstrap script to add the ec2 permissions policy

Chore: [AEA-0000] - Add ec2 permissions to cdk role

---

cloudformation/ci_resources.yml
package-lock.json
package.json

- Adds permission for invoking cdk vpc custom resource lambda

Chore: [AEA-0000] - Add cdk vpc custom resource permissions

---

.github/workflows/ci.yml
.github/workflows/cloudformation.yml
.github/workflows/combine_dependabot_prs.yml
.github/workflows/create_confluence_release_notes.yml
.github/workflows/delete_old_cloudformation_stacks.yml
.github/workflows/dependabot_auto_approve_and_merge.yml
.github/workflows/pr_link.yml
.github/workflows/pr_title_check.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/sam_package_code.yml
.github/workflows/sam_release_code.yml

Fix: [AEA-0000] - pin ubuntu to 22.04

---

cloudformation/ci_resources.yml

- add eps-storage-terraform to oidc client list

Fix: [AEA-0000] - add eps-storage-terraform to oidc clients

---

.gitignore
scripts/set_secrets.sh

- set secret pems in all repos

Fix: [AEA-0000] - set secret pems in all repos

---

cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json

- fix repo name in claim filter

Fix: [AEA-0000] - fix repo name in claim filter

---

cloudformation/ci_resources.yml

Fix: [AEA-0000] - add scaling schedule action permissions

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- add some more permissions needed for deployments

Fix: [AEA-000] - add missing permissions for no error deployments

---

cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json

- permissions so cpt api can pull cdk image

Fix: [AEA-0000] - cdk permissions for cpt api

---

.github/scripts/call_mark_jira_released.sh
.github/scripts/create_changeset_existing_tags.sh
.github/scripts/create_changeset_new_tags.sh
.github/scripts/create_env_release_notes.sh
.github/scripts/describe_changeset.sh
.github/scripts/execute_changeset.sh
.github/scripts/get_current_dev_tag.sh
.github/scripts/get_target_deployed_tag.sh
.github/scripts/release_code.sh

- increase aws cli retries
- check we have variables needed from aws commands before proceeding

Fix: [AEA-0000] - increase aws cli retries

---

cloudformation/secrets.yml

- add secrets for prescription signing private and public key

Fix: [AEA-0000] - add signing cert secrets

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- add permissions to deploy rum resources

Chore: [AEA-0000] - permission to rum

---

cloudformation/ci_resources.yml

- add permissions to get image scan results

Fix: [AEA-0000] - add permissions to get image scan results

---

cloudformation/account_resources.yml

- add more inspector suprressions

Fix: [AEA-0000] - more supressions

---

privateCA/create_certs.sh

- fix create certs for fhir facade

Fix: [AEA-0000] - fix create certs for fhir facade

---

cloudformation/account_resources.yml

- add CVE-2025-23166 and CVE-2025-46701 to scanning exceptions

Fix: [AEA-0000]  - more scanning exceptions

---

SAMtemplates/lambda_resources_bootstrap.yaml

- add a lambda_bootstrap stack definition

Fix: [AEA-0000] - another stack needed to bootstrap 

---

cloudformation/account_resources.yml

- add more inspector supressions

Fix: [AEA-0000] - add more inspector supressions

---

cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/ref.json
scripts/set_secrets.sh

This pull request adds EPS Assist to the list of repositories for setting secrets.

Chore: [AEA-0000] - Add EPS Assist to claim filters for setting secrets

---

cloudformation/account_resources.yml

Fix: [AEA-0000] - more ECR supressions

---

cloudformation/account_resources.yml
cloudformation/account_resources_bootstrap.yml
cloudformation/management.yml

- extend bootstrapping commands
- create a management stack for manual deployment to some accounts
- extend EPSReadOnlyExtraPermissions to allow it to run athena queries

Fix: [AEA-0000] - manual deployment for bootstrapping

---

.github/scripts/create_changeset_existing_tags.sh
.github/scripts/create_changeset_new_tags.sh
.github/scripts/release_code.sh
.github/workflows/ci.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/release_all_stacks.yml
.vscode/account-resources.code-workspace
Makefile
SAMtemplates/lambda_resources.yaml
cloudformation/ci_resources.yml
cloudformation/env/dev.json
cloudformation/env/int.json
cloudformation/env/prod.json
cloudformation/env/qa.json
cloudformation/env/ref.json
package-lock.json
package.json
packages/driftDetector/.vscode/launch.json
packages/driftDetector/.vscode/settings.json
packages/driftDetector/jest.config.ts
packages/driftDetector/jest.debug.config.ts
packages/driftDetector/package.json
packages/driftDetector/src/driftDetector.ts
packages/driftDetector/tsconfig.json
packages/proxygen/jest.config.ts

- add drift detection for cloudformation stacks

Fix: [AEA-0000] - add cloudformation drift detection

---

SAMtemplates/lambda_resources.yaml

Fix: [AEA-0000] - Fix stack drift

---

cloudformation/account_resources.yml

Fix: [AEA-0000] - add new ECR suppression

---

cloudformation/account_resources.yml

- suppress some more cve for validator

Fix: [AEA-0000] - suppress some more CVEs for validator

---

.github/workflows/pr_link.yml

Fix: [AEA-0000] - use sha for gh action

---

cloudformation/secrets.yml
scripts/set_aws_secrets.py

I'm re-jigging which secrets hold what. This PR just updates descriptions, and renames a secret.
Must be merged BEFORE https://github.com/NHSDigital/eps-prescription-status-update-api/pull/2141

Chore: [AEA-0000] - Update descriptions of notify secrets

---

cloudformation/account_resources.yml
cloudformation/ci_resources.yml

- kms access to cloudfront log group
- kms access to waf log group
- permissions to set up logging for cloudfront and waf

Fix: [AEA-0000] - kms access to cloudfront and waf log groups

---

scripts/set_github_secrets.py

New: [AEA-5662] - Adds Semantic Release Workflow Repo

---

cloudformation/account_resources.yml

- Removes unneeded cloudfront logs bucket

Chore: [AEA-4772] - Remove cloudfront logs bucket

---

.github/workflows/cdk_release_code.yml

Fix: [AEA-0000] - fix no initial tag for cdk

---

.github/workflows/cdk_release_code.yml
.github/workflows/release_all_stacks.yml
environmentSettings/int.json
environmentSettings/prod.json

- do not use environment for cdk diff

Fix: [AEA-0000] - do not use an environment for cdk diff
