NHSDigital/electronic-prescription-service-account-resources

- cloudformation/env/int.json
- cloudformation/env/prod.json
Made SubjectClaimFilters more specific so that only int and prod Github envs can assume CloudFormationDeployRoles in int and prod, respectively.
> AEA-3738 Restrict which GitHub envs can deploy to int and prod

- SAMtemplates/lambda_resources.yaml
Part of https://nhsd-jira.digital.nhs.uk/browse/AEA-3735.
The appropriate Lambda Role in PfP could not get created. The culprit was a wrong arn reference which was changed to the PolicyArn. 
> AEA-3735 Enables lambda insights for pfp 

- .github/scripts/delete_stacks.sh
Fixed bug spotted by Ant. Introduced by double quoting in array assignment. Introduced as part of AEA-3622
> Fix delete_old_cloudformation_stacks script

- cloudformation/account_resources.yml
- cloudformation/env/int.json
- cloudformation/env/prod.json
- cloudformation/env/qa.json
- cloudformation/env/ref.json
- adds none filter for test reports in other environments except dev
- adds audit bucket permissions
> add none filter for test report claim in other env apart from dev

- SAMtemplates/lambda_resources.yaml
- cloudformation/account_resources.yml
🎫 [AEA-3878](https://nhsd-jira.digital.nhs.uk/browse/AEA-3878) Create certificates for mutual TLS for PSU API - create secrets
For the prescription status update service, we need certificates and keys created to enable mutual TLS communication to the API gateway endpoint to ensure communication is secure.
Create PSU secrets.
> AEA-3878 Create certificates for mutual TLS for PSU API - create secrets

- SAMtemplates/lambda_resources.yaml
🎫 [AEA-3878](https://nhsd-jira.digital.nhs.uk/browse/AEA-3878) Create certificates for mutual TLS for PSU API - use secrets
For the prescription status update service, we need certificates and keys created to enable mutual TLS communication to the API gateway endpoint to ensure communication is secure.
Use PSU secrets.
> AEA-3878 Create certificates for mutual TLS for PSU API - use secrets

- cloudformation/ci_resources.yml
🎫 [AEA-3907](https://nhsd-jira.digital.nhs.uk/browse/AEA-3907) dynamodb permissions not added to execution role
Add DynamoDB permissions to the execution role.
> AEA-3907 Add DynamoDB permissions to the execution role

- cloudformation/ci_resources.yml
🎫 [AEA-3978](https://nhsd-jira.digital.nhs.uk/browse/AEA-3978) Give the ci role access to all kms keys
Give the ci role access to all kms keys.
> AEA-3978 Give the ci role access to all kms keys

- cloudformation/ci_resources.yml
Adding ssm permissions to allow creation/deletion of Parameter Store params, to be used in toggling in state machines.
> AEA-3899 Add required ssm permissions to CloudFormationExecutionRole.

- packages/splunkProcessor/src/splunkProcessor.js
- packages/splunkProcessor/tests/transformLogEvent.stepfunctions.test.js
- retrieve normalised headers for logging correlation ids for step functions
> Fix: [AEA-0000] - normalise headers for logging correlation ids from step functions

- SAMtemplates/lambda_resources.yaml
- change esbuild to bundle dependencies following default behavior in esbuild 0.22 - https://github.com/evanw/esbuild/releases/tag/v0.22.0
> Fix: [AEA-0000] - change esbuild to bundle dependendencies

- .github/scripts/describe_changeset.sh
- aws returns different status messages when there are no changes in cloudformation
> Fix: [AEA-0000] - add different status reason to ignore when checking changeset

- packages/splunkProcessor/.vscode/settings.json
- packages/splunkProcessor/src/splunkProcessor.js
- packages/splunkProcessor/tests/transformLogEvent.stepfunctions.test.js
- redact input, output, parameters from step function logs before sending to splunk
> Fix: [AEA-4205] - redact step function logs before sending to splunk

- cloudformation/account_resources.yml
🎫 [AEA-4291](https://nhsd-jira.digital.nhs.uk/browse/AEA-4291) Create certificates for mutual TLS for EPS FHIR
For the EPS FHIR, we need certificates and keys to enable mutual TLS communication with the API gateway endpoint, ensuring that the communication is secure.
> Update: [AEA-4291] - Create certificates for mutual TLS for EPS FHIR - create secrets

- SAMtemplates/lambda_resources.yaml
🎫 [AEA-4291](https://nhsd-jira.digital.nhs.uk/browse/AEA-4291) Create certificates for mutual TLS for EPS FHIR
For the EPS FHIR, we need certificates and keys to enable mutual TLS communication with the API gateway endpoint, ensuring that the communication is secure.
Use EPS secrets.
> Update: [AEA-4291] - Create certificates for mutual TLS for EPS FHIR - use secrets

- cloudformation/account_resources.yml
🎫 [AEA-4382](https://nhsd-jira.digital.nhs.uk/browse/AEA-4382) Add the pattern for ECS CloudWatchLogsKmsKey to the account-resources stack
Add the pattern for ECS CloudWatchLogsKmsKey to the account-resources stack
> Chore: [AEA-4382] - Add the pattern for ECS CloudWatchLogsKmsKey to the account-resources stack

- packages/slackAlerter/src/slackAlerter.ts
- packages/slackAlerter/tests/testContentFormatting.test.ts
- packages/slackAlerter/tests/testSlackAlerter.test.ts
- packages/slackAlerter/tests/utils/testUtils.ts
- Updates alarm name parsing to match new `<StackName>_<ResourceName>_<Metric>` format
- Updates tests
> Chore: [AEA-4440] - Update Slack Alerter alarm name parsing

- .github/workflows/ci.yml
- .vscode/account-resources.code-workspace
- cloudformation/artillery_resources.yml
A secret I thought was stored in Github was actually an AWS secret. This adds it in.
Rather than wait for another release cut, there is also a change to the CI workflow that forces a release to REF.
> Fix: [AEA-4067] - Add missing secret

- cloudformation/ci_resources.yml
- no need for account id in s3 resource
> Fix: [AEA-4495] - no account id in s3

- cloudformation/ci_resources.yml
🎫 [AEA-4565](https://nhsd-jira.digital.nhs.uk/browse/AEA-4565) Grant Stack Permissions to CloudFormation Execution Role
Grant Stack Permissions to CloudFormation Execution Role
> Chore: [AEA-4565] - Grant Stack Permissions to CloudFormation Execution Role

- cloudformation/secrets.yml
🎫 [AEA-4732](https://nhsd-jira.digital.nhs.uk/browse/AEA-4732) Amend Proxygen key outputs for the EPS FHIR API
Update the Proxygen key outputs for the EPS FHIR API to ensure they return the correct values.
> Fix: [AEA-4732] - Amend Proxygen key outputs for the EPS FHIR API

- cloudformation/ci_resources.yml
- add permissions for cdk push image role to list scan and coverage findings
> Fix: [AEA-0000] - permissions for cdk push image to list scan coverage and findings

- cloudformation/secrets.yml
The NHS Notify endpoint needs an OAUTH2 bearer token. This adds some secrets necessary to making that work.
> Fix: [AEA-0000] - Add missing notify secrets

- packages/proxygen/src/helpers.ts
- packages/proxygen/tests/proxygenInstanceDelete.test.ts
- packages/proxygen/tests/proxygenInstanceGet.test.ts
- limit proxygen error logging to only log first 255 chars of request body to prevent log loss
> Fix: [AEA-0000] - limit proxygen error logging to not log full request body

- packages/cdk/resources/InspectorFilters.ts
This pull request adds suppression for CVE-2025-9230, as it is not applicable. We do not use password-based encryption in CMS messages.
> Chore: [AEA-0000] - Add suppression for CVE-2025-9230
